{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyMGnhSH3HfYv9JfC6FNS0b/",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "ir",
      "display_name": "R"
    },
    "language_info": {
      "name": "R"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/BaileyMeche/Econometrics/blob/main/InstrumentalVariables.r\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "# Instrumental Variables"
      ],
      "metadata": {
        "id": "NRxZSc-y0Gm3"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "install.packages('causaldata')\n",
        "install.packages('modelsummary')\n",
        "install.packages('gmm')\n",
        "install.packages(\"htmltools\")\n",
        "install.packages(\"fixest\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "ARxOGZuMpjcw",
        "outputId": "a5c934c6-e40e-4849-fc2a-7abd21de76c3"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "Installing package into ‘/usr/local/lib/R/site-library’\n",
            "(as ‘lib’ is unspecified)\n",
            "\n",
            "Installing package into ‘/usr/local/lib/R/site-library’\n",
            "(as ‘lib’ is unspecified)\n",
            "\n",
            "also installing the dependencies ‘webshot’, ‘bayestestR’, ‘datawizard’, ‘checkmate’, ‘kableExtra’, ‘insight’, ‘parameters’, ‘performance’, ‘tables’\n",
            "\n",
            "\n",
            "Installing package into ‘/usr/local/lib/R/site-library’\n",
            "(as ‘lib’ is unspecified)\n",
            "\n",
            "also installing the dependencies ‘zoo’, ‘sandwich’\n",
            "\n",
            "\n",
            "Installing package into ‘/usr/local/lib/R/site-library’\n",
            "(as ‘lib’ is unspecified)\n",
            "\n",
            "Installing package into ‘/usr/local/lib/R/site-library’\n",
            "(as ‘lib’ is unspecified)\n",
            "\n",
            "also installing the dependencies ‘Formula’, ‘numDeriv’, ‘Rcpp’, ‘dreamerr’\n",
            "\n",
            "\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "install.packages(\"htmltools\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "NIkcBAKHQoeC",
        "outputId": "c250a7c9-d422-41e9-b9f1-e89796a18cba"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "Installing package into ‘/usr/local/lib/R/site-library’\n",
            "(as ‘lib’ is unspecified)\n",
            "\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "library(modelsummary);library(IRdisplay)\n",
        "library(gmm)\n",
        "library(sandwich)\n",
        "library(dplyr)  # Load the dplyr package"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "x39JhXZ8Qlv0",
        "outputId": "a725f435-7f51-4157-bc1c-254d5c32ee71"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "Loading required package: sandwich\n",
            "\n",
            "\n",
            "Attaching package: ‘dplyr’\n",
            "\n",
            "\n",
            "The following objects are masked from ‘package:stats’:\n",
            "\n",
            "    filter, lag\n",
            "\n",
            "\n",
            "The following objects are masked from ‘package:base’:\n",
            "\n",
            "    intersect, setdiff, setequal, union\n",
            "\n",
            "\n"
          ]
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "## Instrumental Variables Estimators"
      ],
      "metadata": {
        "id": "DQZz9nXZtx5z"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "### “Social Networks and the Decision to Insure” by Cai, De Janvry, and Sadoulet 2015.\n",
        "* The authors are looking into the decision that farmers make about whether to buy insurance against weather events. In particular, they’re interested in whether information about insurance travels through social networks.\n",
        "\n",
        "* The question then is: how much does what your friends learn about insurance affect your own takeup of insurance?\n",
        "\n",
        "* We want to identify the effect on `FriendsPurchaseBehavior` on `YourPurchaseBehavior` amond people in the second-round sessions\n",
        "\n",
        "* As an instrument for `FriendsPurchaseBehavior`\n",
        " they use the variable `FirstroundDefault`,  which is a binary indicator for whether your friends were randomly assigned to a “default buy” informational session, where attendees were assigned to buy insurance by default, and had to specify their preference not to buy it, or a “default no buy” session, where attendees were assigned to not buy insurance by default, and had to specify their preference to buy it."
      ],
      "metadata": {
        "id": "TgPFlptvPWbg"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# There are many ways to run 2SLS;\n",
        "# the most common is ivreg from the AER package.\n",
        "# But we'll use feols from fixest for speed and ease\n",
        "# of fixed-effects additions later\n",
        "library(tidyverse); library(modelsummary); library(fixest)\n",
        "d <- causaldata::social_insure\n",
        "\n",
        "# Include just the outcome and controls first, then endogenous ~ instrument\n",
        "# in the second part, and for this study we cluster on address\n",
        "m <- feols(takeup_survey ~ male + age + agpop + ricearea_2010 +\n",
        "            literacy + intensive + risk_averse + disaster_prob +\n",
        "            factor(village) | pre_takeup_rate ~ default,\n",
        "            cluster = ~address, data = d)\n",
        "\n",
        "# Show the first and second stage, omitting all\n",
        "# the controls for ease of visibility\n",
        "results <- msummary(list('First Stage' = m$iv_first_stage[[1]],\n",
        "                'Second Stage' = m),\n",
        "                coef_map = c(default = 'First Round Default',\n",
        "                fit_pre_takeup_rate = 'Friends Purchase Behavior'),\n",
        "                stars = c('*' = .1, '**' = .05, '***' = .01))\n",
        "\n",
        "display_html(toString(results))"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 330
        },
        "id": "wHGAh4Tto83t",
        "outputId": "a826a110-347c-4fdc-b10b-58a1c6d02ef1"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "NOTE: 32 observations removed because of NA values (RHS: 32).\n",
            "\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "text/html": [
              "<table style=\"NAborder-bottom: 0; width: auto !important; margin-left: auto; margin-right: auto;\" class=\"table\">\n",
              " <thead>\n",
              "  <tr>\n",
              "   <th style=\"text-align:left;\">   </th>\n",
              "   <th style=\"text-align:center;\"> First Stage </th>\n",
              "   <th style=\"text-align:center;\"> Second Stage </th>\n",
              "  </tr>\n",
              " </thead>\n",
              "<tbody>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> First Round Default </td>\n",
              "   <td style=\"text-align:center;\"> 0.118*** </td>\n",
              "   <td style=\"text-align:center;\">  </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.034) </td>\n",
              "   <td style=\"text-align:center;\">  </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> Friends Purchase Behavior </td>\n",
              "   <td style=\"text-align:center;\">  </td>\n",
              "   <td style=\"text-align:center;\"> 0.791*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;box-shadow: 0px 1.5px\">  </td>\n",
              "   <td style=\"text-align:center;box-shadow: 0px 1.5px\">  </td>\n",
              "   <td style=\"text-align:center;box-shadow: 0px 1.5px\"> (0.273) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> Num.Obs. </td>\n",
              "   <td style=\"text-align:center;\"> 1378 </td>\n",
              "   <td style=\"text-align:center;\"> 1378 </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> R2 </td>\n",
              "   <td style=\"text-align:center;\"> 0.469 </td>\n",
              "   <td style=\"text-align:center;\"> 0.127 </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> R2 Adj. </td>\n",
              "   <td style=\"text-align:center;\"> 0.448 </td>\n",
              "   <td style=\"text-align:center;\"> 0.092 </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> AIC </td>\n",
              "   <td style=\"text-align:center;\"> −775.7 </td>\n",
              "   <td style=\"text-align:center;\"> 1911.4 </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> BIC </td>\n",
              "   <td style=\"text-align:center;\"> −498.6 </td>\n",
              "   <td style=\"text-align:center;\"> 2188.5 </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> RMSE </td>\n",
              "   <td style=\"text-align:center;\"> 0.18 </td>\n",
              "   <td style=\"text-align:center;\"> 0.47 </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> Std.Errors </td>\n",
              "   <td style=\"text-align:center;\"> by: address </td>\n",
              "   <td style=\"text-align:center;\"> by: address </td>\n",
              "  </tr>\n",
              "</tbody>\n",
              "<tfoot><tr><td style=\"padding: 0; \" colspan=\"100%\">\n",
              "<sup></sup> * p &lt; 0.1, ** p &lt; 0.05, *** p &lt; 0.01</td></tr></tfoot>\n",
              "</table>"
            ]
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "This gives us the result in Table 19.1 (keeping in mind this table doesn’t show a bunch of coefficients for all the control variables).\n",
        " The first stage regression has the endogenous variable (whether your friends purchased insurance) as the dependent variable, and a coefficient for our instrument. The coefficient is 0.118 and statistically significant. It’s showing that your friends being assigned to the “default-purchase” experimental condition leads to a 11.8 percentage point increase in the probability that they’ll buy insurance. We predict whether your friends bought insurance using that .118 bump (as well as the other predictors not shown on the table) and use those predicted values in the second stage."
      ],
      "metadata": {
        "id": "Qk-LWHbjpKaZ"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "The second stage has the actual outcome of you buying insurance as the outcome. A one-unit increase in the rate at which your friends buy insurance, using only the random variation driven by the random experimental assignment and the controls, increases your chances of buying insurance by .791. That’s a pretty strong spillover effect!\n",
        "\n"
      ],
      "metadata": {
        "id": "ELm-RBahpc7s"
      }
    },
    {
      "cell_type": "markdown",
      "source": [
        "## GMM and LIML"
      ],
      "metadata": {
        "id": "C2pq1Yqos7Je"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "\n",
        "\n",
        "d <- causaldata::social_insure\n",
        "\n",
        "# Remove all missing observations ourselves\n",
        "d <- d %>%\n",
        "    select(takeup_survey, male, age, agpop, ricearea_2010,\n",
        "           literacy, intensive, risk_averse, disaster_prob,\n",
        "           village, address, pre_takeup_rate, default) %>%\n",
        "    na.omit()\n",
        "\n",
        "m <- gmm(takeup_survey ~ male + age + agpop + ricearea_2010 +\n",
        "         literacy + intensive + risk_averse + disaster_prob +\n",
        "         factor(village) + pre_takeup_rate,\n",
        "         ~ male + age + agpop + ricearea_2010 +\n",
        "         literacy + intensive + risk_averse + disaster_prob +\n",
        "         factor(village) + default, data = d)\n",
        "\n",
        "# We can apply the address clustering most easily in msummary\n",
        "results <- msummary(m, vcov = ~address, stars = c('*' = .1, '**' = .05, '***' = .01))\n",
        "\n",
        "display_html(toString(results))"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "id": "6bXkq0Dopb8I",
        "outputId": "b2516e09-5d2c-4afe-c23a-a903d88c825e"
      },
      "execution_count": null,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/html": [
              "<table style=\"NAborder-bottom: 0; width: auto !important; margin-left: auto; margin-right: auto;\" class=\"table\">\n",
              " <thead>\n",
              "  <tr>\n",
              "   <th style=\"text-align:left;\">   </th>\n",
              "   <th style=\"text-align:center;\">  (1) </th>\n",
              "  </tr>\n",
              " </thead>\n",
              "<tbody>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> (Intercept) </td>\n",
              "   <td style=\"text-align:center;\"> 0.020 </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.129) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> male </td>\n",
              "   <td style=\"text-align:center;\"> 0.038 </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.047) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> age </td>\n",
              "   <td style=\"text-align:center;\"> 0.005*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.001) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> agpop </td>\n",
              "   <td style=\"text-align:center;\"> −0.002 </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.006) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> ricearea_2010 </td>\n",
              "   <td style=\"text-align:center;\"> 0.003*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.001) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> literacy </td>\n",
              "   <td style=\"text-align:center;\"> 0.082** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.036) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> intensive </td>\n",
              "   <td style=\"text-align:center;\"> −0.009 </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.026) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> risk_averse </td>\n",
              "   <td style=\"text-align:center;\"> 0.237*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.044) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> disaster_prob </td>\n",
              "   <td style=\"text-align:center;\"> 0.001* </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.001) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)beixing </td>\n",
              "   <td style=\"text-align:center;\"> −0.493*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.112) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)caijia </td>\n",
              "   <td style=\"text-align:center;\"> −0.393*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.128) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)daqiao </td>\n",
              "   <td style=\"text-align:center;\"> −0.494** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.219) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)daxi </td>\n",
              "   <td style=\"text-align:center;\"> −0.271*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.102) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)dayu </td>\n",
              "   <td style=\"text-align:center;\"> −0.329*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.111) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)dazhou </td>\n",
              "   <td style=\"text-align:center;\"> −0.506*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.100) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)dongan </td>\n",
              "   <td style=\"text-align:center;\"> −0.428*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.152) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)dukou </td>\n",
              "   <td style=\"text-align:center;\"> −0.499*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.111) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)fusheng </td>\n",
              "   <td style=\"text-align:center;\"> −0.439*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.139) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)fuzhou </td>\n",
              "   <td style=\"text-align:center;\"> −0.438*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.168) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)gangtou </td>\n",
              "   <td style=\"text-align:center;\"> −0.417*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.117) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)gangxia </td>\n",
              "   <td style=\"text-align:center;\"> −0.213 </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.166) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)guojia </td>\n",
              "   <td style=\"text-align:center;\"> −0.109 </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.124) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)hefeng </td>\n",
              "   <td style=\"text-align:center;\"> −0.368*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.091) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)helin </td>\n",
              "   <td style=\"text-align:center;\"> −0.367*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.137) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)hongxing </td>\n",
              "   <td style=\"text-align:center;\"> −0.342*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.109) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)huangshan </td>\n",
              "   <td style=\"text-align:center;\"> −0.394*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.148) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)jingang </td>\n",
              "   <td style=\"text-align:center;\"> −0.465*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.101) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)jinggang </td>\n",
              "   <td style=\"text-align:center;\"> −0.200** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.092) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)lianqian </td>\n",
              "   <td style=\"text-align:center;\"> −0.352*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.125) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)lianxing </td>\n",
              "   <td style=\"text-align:center;\"> −0.331** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.168) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)longqing </td>\n",
              "   <td style=\"text-align:center;\"> −0.385** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.166) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)lusikou </td>\n",
              "   <td style=\"text-align:center;\"> 0.016 </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.173) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)mazhou </td>\n",
              "   <td style=\"text-align:center;\"> −0.378** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.176) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)minzhu </td>\n",
              "   <td style=\"text-align:center;\"> −0.294*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.095) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)shigang </td>\n",
              "   <td style=\"text-align:center;\"> −0.336** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.142) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)wanshang </td>\n",
              "   <td style=\"text-align:center;\"> −0.565*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.185) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)xiabao </td>\n",
              "   <td style=\"text-align:center;\"> −0.447 </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.278) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)xianghu </td>\n",
              "   <td style=\"text-align:center;\"> −0.168 </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.173) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)xiaofang </td>\n",
              "   <td style=\"text-align:center;\"> −0.273** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.138) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)xiashatou </td>\n",
              "   <td style=\"text-align:center;\"> −0.185 </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.139) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)xiecheng </td>\n",
              "   <td style=\"text-align:center;\"> −0.388*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.131) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)xihe </td>\n",
              "   <td style=\"text-align:center;\"> −0.433*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.094) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)xihu </td>\n",
              "   <td style=\"text-align:center;\"> −0.507*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.177) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)xilian </td>\n",
              "   <td style=\"text-align:center;\"> −0.151 </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.114) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)xinguang </td>\n",
              "   <td style=\"text-align:center;\"> −0.416*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.111) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)xingzeng </td>\n",
              "   <td style=\"text-align:center;\"> −0.272** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.138) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)xinlian </td>\n",
              "   <td style=\"text-align:center;\"> −0.483*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.084) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)yanjiang </td>\n",
              "   <td style=\"text-align:center;\"> −0.461** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.185) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)yazhou </td>\n",
              "   <td style=\"text-align:center;\"> −0.290*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.107) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)yongfeng </td>\n",
              "   <td style=\"text-align:center;\"> −0.509*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.140) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)zhangxi </td>\n",
              "   <td style=\"text-align:center;\"> −0.301*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.099) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> factor(village)zixi </td>\n",
              "   <td style=\"text-align:center;\"> −0.345*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\">  </td>\n",
              "   <td style=\"text-align:center;\"> (0.107) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> pre_takeup_rate </td>\n",
              "   <td style=\"text-align:center;\"> 0.791*** </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;box-shadow: 0px 1.5px\">  </td>\n",
              "   <td style=\"text-align:center;box-shadow: 0px 1.5px\"> (0.251) </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> Num.Obs. </td>\n",
              "   <td style=\"text-align:center;\"> 1378 </td>\n",
              "  </tr>\n",
              "  <tr>\n",
              "   <td style=\"text-align:left;\"> Std.Errors </td>\n",
              "   <td style=\"text-align:center;\"> by: address </td>\n",
              "  </tr>\n",
              "</tbody>\n",
              "<tfoot><tr><td style=\"padding: 0; \" colspan=\"100%\">\n",
              "<sup></sup> * p &lt; 0.1, ** p &lt; 0.05, *** p &lt; 0.01</td></tr></tfoot>\n",
              "</table>"
            ]
          },
          "metadata": {}
        }
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Finally, what if we have a lot of fixed effects in our IV model? There are some technical adjustments that must be made in these cases.  The feols() function we already used can easily incorporate fixed effects - the` +factor(village)` just becomes `| village`. Stata and Python aren’t too hard though. In Stata you switch from ivregress to xtivreg. This comes with a few other changes - you must xtset your data to tell Stata what the panel structure is, it only does 2SLS rather than GMM or LIML, and you must tell it whether you want fixed effects (fe), random effects (re), or something else (see the help file). At the moment there is no Python equivalent for this, although our typical Python syntax will let you estimate IV models with fixed effects in them by adding sets of binary indicator variables.\n",
        "\n"
      ],
      "metadata": {
        "id": "4B5WkaToptQO"
      }
    }
  ]
}